
# Using the Python base image
FROM python:3.11-bookworm

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="umitools"
LABEL org.opencontainers.image.description="Container image for the use of umi_tools in Fred Hutch OCDO's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://ocdo.fredhutch.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Set the shell option to fail if any command in a pipe fails
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Installing prerequisites for samtools
RUN apt-get update \
  && BE_VERSION=$(apt-cache policy build-essential | grep Candidate | awk '{print $2}') \
  && WGET_VERSION=$(apt-cache policy wget | grep Candidate | awk '{print $2}') \
  && CERT_VERSION=$(apt-cache policy ca-certificates | grep Candidate | awk '{print $2}') \
  && LIBNCURSES_VERSION=$(apt-cache policy libncurses-dev | grep Candidate | awk '{print $2}') \
  && ZLIB_VERSION=$(apt-cache policy zlib1g-dev | grep Candidate | awk '{print $2}') \
  && LIBBZ2_VERSION=$(apt-cache policy libbz2-dev | grep Candidate | awk '{print $2}') \
  && LIBLZMA_VERSION=$(apt-cache policy liblzma-dev | grep Candidate | awk '{print $2}') \
  && LIBSSL_VERSION=$(apt-cache policy libssl-dev | grep Candidate | awk '{print $2}') \
  && LIBCURL_VERSION=$(apt-cache policy libcurl4-gnutls-dev | grep Candidate | awk '{print $2}') \
  && apt-get install -y --no-install-recommends \
  build-essential="${BE_VERSION}" \
  wget="${WGET_VERSION}" \
  ca-certificates="${CERT_VERSION}" \
  libncurses-dev="${LIBNCURSES_VERSION}" \
  zlib1g-dev="${ZLIB_VERSION}" \
  libbz2-dev="${LIBBZ2_VERSION}" \
  liblzma-dev="${LIBLZMA_VERSION}" \
  libssl-dev="${LIBSSL_VERSION}" \
  libcurl4-gnutls-dev="${LIBCURL_VERSION}" \
  && rm -rf /var/lib/apt/lists/*

# Build and install samtools
RUN wget -q https://github.com/samtools/samtools/releases/download/1.20/samtools-1.20.tar.bz2 && tar -jxf samtools-1.20.tar.bz2
WORKDIR /samtools-1.20
RUN ./configure && make && make install
WORKDIR /
RUN rm -rf samtools-1.20* && ldconfig

# Installing umi_tools via pip
RUN pip install --no-cache-dir umi_tools==1.1.6

# Smoke test to verify both tools work
RUN umi_tools --version && samtools --version
