
# Using the Ubuntu base image
FROM ubuntu:18.04

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="umitools"
LABEL org.opencontainers.image.description="Docker image for the use of umi_tools in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

ARG PACKAGE_VERSION=1.0.1
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install --yes python3-pip && \
    pip3 install --upgrade pip && \
    pip3 install umi_tools==$PACKAGE_VERSION && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/local/bin/python
