
# Using the Ubuntu base image
FROM python:3.9.19-bookworm

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="umitools"
LABEL org.opencontainers.image.description="Docker image for the use of umi_tools in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="1.0.1"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Pulling and extracting STAR source code
RUN wget -q --no-check-certificate https://github.com/CGATOxford/UMI-tools/archive/refs/tags/1.0.1.tar.gz && tar -xzf 1.0.1.tar.gz

# Installing STAR
WORKDIR /UMI-tools-1.0.1
RUN python setup.py install
WORKDIR /

# Cleanup
RUN rm -rf UMI-tools-1.0.1 1.0.1.tar.gz
