
# Using the Ubuntu base image
FROM python:3.9.19-bookworm

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="umitools"
LABEL org.opencontainers.image.description="Container image for the use of umi_tools in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Installing prerequisites
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential wget \
  zlib1g-dev autoconf=2.71-3 automake \
  libncurses-dev libbz2-dev liblzma-dev \
  libssl-dev libcurl4-gnutls-dev xxd \
  && rm -rf /var/lib/apt/lists/*

# Pulling and extracting STAR source code
RUN wget -q --no-check-certificate https://github.com/CGATOxford/UMI-tools/archive/refs/tags/1.0.1.tar.gz && tar -xzf 1.0.1.tar.gz

# Installing STAR
WORKDIR /UMI-tools-1.0.1
RUN python setup.py install
WORKDIR /
# ENV PATH="${PATH}:/STAR-2.7.6a/source"

# # Pulling and extracting Samtools source code
# RUN wget -q --no-check-certificate https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2 && tar -jxf samtools-1.11.tar.bz2

# # Installing Samtools
# WORKDIR /samtools-1.11
# RUN ./configure && make && make install
# WORKDIR /

# # Cleanup
# RUN rm -rf samtools-1.11 1.0.1.tar.gz
