
# Use Bioconductor base image
FROM bioconductor/bioconductor_docker:RELEASE_3_17

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="deseq2"
LABEL org.opencontainers.image.description="Docker image for DESeq2 RNA-seq differential expression analysis in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Set the shell option to fail if any command in a pipe fails
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install required R packages
RUN R -e "BiocManager::install(c('DESeq2', 'apeglm', 'pheatmap', 'RColorBrewer'), update=FALSE)" \
  && R -e "install.packages(c('optparse', 'ggplot2', 'dplyr'), repos='https://cloud.r-project.org/')" \
  && apt-get update \
  && LIBXT6_VERSION=$(apt-cache policy libxt6 | grep Candidate | awk '{print $2}') \
  && CAIRO_VERSION=$(apt-cache policy libcairo2-dev | grep Candidate | awk '{print $2}') \
  && LIBXTDEV_VERSION=$(apt-cache policy libxt-dev | grep Candidate | awk '{print $2}') \
  && apt-get install -y --no-install-recommends \
  libxt6="${LIBXT6_VERSION}" \
  libcairo2-dev="${CAIRO_VERSION}" \
  libxt-dev="${LIBXTDEV_VERSION}" \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Copy the DESeq2 analysis script to the container
COPY deseq2/deseq2_analysis.R /deseq2_analysis.R
RUN chmod +x /deseq2_analysis.R

# Set working directory
WORKDIR /data

# Default command
CMD ["Rscript", "--help"]
