
FROM ubuntu:noble-20240114
LABEL org.opencontainers.image.source=https://github.com/getwilds/fastq-to-cram
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.description="Container image for the use of samtools in FH DaSL's WILDS"
LABEL org.opencontainers.image.licenses=MIT
RUN apt-get update \
  && apt-get install -y build-essential wget zlib1g-dev autoconf automake libncurses5-dev libbz2-dev liblzma-dev libssl-dev libcurl4-gnutls-dev \
  && rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2
RUN tar -jxf samtools-1.11.tar.bz2
WORKDIR /samtools-1.11
RUN ./configure && make && make install
WORKDIR /
RUN rm -rf samtools-1.11 samtools-1.11.tar.bz2

