# Using the Miniconda base image with SHA for reproducibility
FROM condaforge/miniforge3:24.7.1-2@sha256:666f4ae3d2596c25e9cd4e4d6eaa551aa63245a02dae450a9e2ee2e944ce0dc2

# Set shell to use bash with pipefail option
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Set version numbers for easy updating
ENV GATK_VERSION=4.3.0.0 \
    SAMTOOLS_VERSION=1.11

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="gatk" \
      org.opencontainers.image.description="Container image for the use of GATK in FH DaSL's WILDS" \
      org.opencontainers.image.version="latest" \
      org.opencontainers.image.authors="wilds@fredhutch.org" \
      org.opencontainers.image.url=https://hutchdatascience.org/ \
      org.opencontainers.image.documentation=https://getwilds.org/ \
      org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library \
      org.opencontainers.image.licenses=MIT

# Installing GATK with conda
RUN conda config --set always_copy true \
    && conda install -y --channel bioconda gatk4="${GATK_VERSION}" \
    && conda clean -afy

# Create build directory and get package versions
WORKDIR /build

RUN apt-get update \
    && BUILD_ESSENTIAL_VERSION="$(apt-cache policy build-essential | grep Candidate | awk '{print $2}')" \
    && WGET_VERSION="$(apt-cache policy wget | grep Candidate | awk '{print $2}')" \
    && ZLIB_VERSION="$(apt-cache policy zlib1g-dev | grep Candidate | awk '{print $2}')" \
    && AUTOCONF_VERSION="$(apt-cache policy autoconf | grep Candidate | awk '{print $2}')" \
    && AUTOMAKE_VERSION="$(apt-cache policy automake | grep Candidate | awk '{print $2}')" \
    && LIBNCURSES_VERSION="$(apt-cache policy libncurses5-dev | grep Candidate | awk '{print $2}')" \
    && LIBBZ2_VERSION="$(apt-cache policy libbz2-dev | grep Candidate | awk '{print $2}')" \
    && LIBLZMA_VERSION="$(apt-cache policy liblzma-dev | grep Candidate | awk '{print $2}')" \
    && LIBSSL_VERSION="$(apt-cache policy libssl-dev | grep Candidate | awk '{print $2}')" \
    && LIBCURL_VERSION="$(apt-cache policy libcurl4-gnutls-dev | grep Candidate | awk '{print $2}')" \
    && apt-get install -y --no-install-recommends \
        build-essential="${BUILD_ESSENTIAL_VERSION}" \
        wget="${WGET_VERSION}" \
        zlib1g-dev="${ZLIB_VERSION}" \
        autoconf="${AUTOCONF_VERSION}" \
        automake="${AUTOMAKE_VERSION}" \
        libncurses5-dev="${LIBNCURSES_VERSION}" \
        libbz2-dev="${LIBBZ2_VERSION}" \
        liblzma-dev="${LIBLZMA_VERSION}" \
        libssl-dev="${LIBSSL_VERSION}" \
        libcurl4-gnutls-dev="${LIBCURL_VERSION}" \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && wget -q --no-check-certificate "https://github.com/samtools/samtools/releases/download/${SAMTOOLS_VERSION}/samtools-${SAMTOOLS_VERSION}.tar.bz2" \
    && tar -jxf "samtools-${SAMTOOLS_VERSION}.tar.bz2"

# Configure and install Samtools
WORKDIR /build/samtools-${SAMTOOLS_VERSION}
RUN ./configure \
    && make \
    && make install \
    && rm -rf /build \
    && useradd -m -s /bin/bash gatk

# Switch to non-root user and set final working directory
USER gatk
WORKDIR /data
