
# Using the Miniconda base image
FROM continuumio/miniconda3:24.1.2-0

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="gatk"
LABEL org.opencontainers.image.description="Container image for the use of GATK in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="4.3.0.0"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Installing GATK via conda
RUN conda install -y -c bioconda gatk4=4.3.0.0

# Installing Samtools prerequisites
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential=12.9 wget=1.21-1+deb11u1 \
  zlib1g-dev=1:1.2.11.dfsg-2+deb11u2 autoconf=2.69-14 automake=1:1.16.3-2 \
  libncurses5-dev=6.2+20201114-2+deb11u2 libbz2-dev=1.0.8-4 liblzma-dev=5.2.5-2.1~deb11u1 \
  libssl-dev=1.1.1w-0+deb11u1 libcurl4-gnutls-dev=7.74.0-1.3+deb11u11 \
  && rm -rf /var/lib/apt/lists/*

# Pulling and extracting Samtools source code
RUN wget -q --no-check-certificate https://github.com/samtools/samtools/releases/download/1.11/samtools-1.11.tar.bz2 && tar -jxf samtools-1.11.tar.bz2

# Installing Samtools
WORKDIR /samtools-1.11
RUN ./configure && make && make install
WORKDIR /

# Cleanup
RUN rm -rf samtools-1.11 samtools-1.11.tar.bz2
