
# Using the Ubuntu base image
FROM ubuntu:24.04

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="gatk"
LABEL org.opencontainers.image.description="Container image for the use of GATK in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://ocdo.fredhutch.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Set environment variables
ENV GATK_VERSION=4.6.1.0
ENV GATK_HOME=/opt/gatk

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    git \
    python3 \
    python3-pip \
    curl \
    samtools \
    tzdata \
    software-properties-common \
    && add-apt-repository -y ppa:openjdk-r/ppa \
    && apt-get update \
    && apt-get install -y openjdk-17-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && ln -sf /usr/bin/python3 /usr/bin/python

# Download and install GATK
RUN mkdir -p ${GATK_HOME} && \
    wget -q https://github.com/broadinstitute/gatk/releases/download/${GATK_VERSION}/gatk-${GATK_VERSION}.zip && \
    unzip gatk-${GATK_VERSION}.zip -d /opt && \
    rm gatk-${GATK_VERSION}.zip && \
    ln -s /opt/gatk-${GATK_VERSION}/gatk /usr/local/bin/gatk

# Verify installation
RUN gatk --version

# Create working directory
WORKDIR /data

# Add helpful message on startup
RUN echo 'echo "GATK Docker Container - Version ${GATK_VERSION}\nUsage: gatk --help"' >> /root/.bashrc

# Command to run when container starts
CMD ["/bin/bash"]
