FROM r-base:4.4.0

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="seurat"
LABEL org.opencontainers.image.description="Container image for the use of Seurat in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Installing prerequisites
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential=12.10 \
  zlib1g-dev=1:1.3.dfsg-3.1 autoconf=2.71-3 automake=1:1.16.5-1.3 \
  libncurses-dev libbz2-dev=1.0.8-5.1 liblzma-dev=5.6.1+really5.4.5-1 \
  libssl-dev=3.2.1-3 libcurl4-gnutls-dev=8.7.1-3 \
  && rm -rf /var/lib/apt/lists/*

# Installing Seurat R package
RUN Rscript -e "install.packages('remotes')" && \
    Rscript -e "remotes::install_github('satijalab/seurat', 'seurat5', quiet = TRUE)"
