
# Using the Ubuntu base image
FROM ubuntu:oracular-20241009

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="picard"
LABEL org.opencontainers.image.description="Container image for the use of Picard in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Setting environment variables
ENV DEBIAN_FRONTEND noninteractive

# Installing Java
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jdk=17.0.12+7-2 \
    ant=1.10.14-1 wget=1.24.5-1ubuntu2 r-base=4.4.1-1 ca-certificates-java=20240118 \
    && rm -rf /var/lib/apt/lists/* \
    && update-ca-certificates -f;
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/
RUN export JAVA_HOME

# Pulling Picard jar to a location that will persist in Apptainer
RUN mkdir /usr/picard && wget -q --no-check-certificate -P /usr/picard/ \
https://github.com/broadinstitute/picard/releases/download/3.1.1/picard.jar

