
# Using the Ubuntu base image
FROM ubuntu:24.04

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="picard"
LABEL org.opencontainers.image.description="Container image for the use of Picard in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://ocdo.fredhutch.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Set the shell option to fail if any command in a pipe fails
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Setting environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Installing Java
RUN apt-get update \
  && OPENJDK_VERSION=$(apt-cache policy openjdk-17-jdk | grep Candidate | awk '{print $2}') \
  && WGET_VERSION=$(apt-cache policy wget | grep Candidate | awk '{print $2}') \
  && ANT_VERSION=$(apt-cache policy ant | grep Candidate | awk '{print $2}') \
  && RBASE_VERSION=$(apt-cache policy r-base | grep Candidate | awk '{print $2}') \
  && CACERT_VERSION=$(apt-cache policy ca-certificates-java | grep Candidate | awk '{print $2}') \
  && apt-get install -y --no-install-recommends \
  openjdk-17-jdk="${OPENJDK_VERSION}" \
  ant="${ANT_VERSION}" \
  wget="${WGET_VERSION}" \
  r-base="${RBASE_VERSION}" \
  ca-certificates-java="${CACERT_VERSION}" \
  && rm -rf /var/lib/apt/lists/* \
  && update-ca-certificates -f;
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
RUN export JAVA_HOME

# Pulling Picard jar to a location that will persist in Apptainer
RUN mkdir /usr/picard && wget -q --no-check-certificate -P /usr/picard/ \
https://github.com/broadinstitute/picard/releases/download/3.1.1/picard.jar

