
# Using the Ubuntu base image
FROM ubuntu:jammy-20240212

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="picard"
LABEL org.opencontainers.image.description="Container image for the use of Picard in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Setting environment variables
ENV DEBIAN_FRONTEND noninteractive

# Installing Java
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get install -y ant && \
    apt-get install -y wget && \
    apt-get install -y r-base && \
    apt-get clean;

# Updating Java certificates
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64/
RUN export JAVA_HOME

# Pulling Picard jar to a location that will persist in Apptainer
RUN mkdir /usr/picard
RUN wget -P /usr/picard/ https://github.com/broadinstitute/picard/releases/download/3.1.1/picard.jar
