# Using the Ubuntu base image
FROM python:2.7-slim

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="manta"
LABEL org.opencontainers.image.description="Container image for the use of Manta structural variant caller in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="1.6.0"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://ocdo.fredhutch.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Set the shell option to fail if any command in a pipe fails
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Update sources.list to use Debian archive (Buster is EOL)
RUN sed -i 's|http://deb.debian.org|http://archive.debian.org|g' /etc/apt/sources.list \
  && sed -i 's|http://security.debian.org|http://archive.debian.org|g' /etc/apt/sources.list \
  && sed -i '/buster-updates/d' /etc/apt/sources.list

# Installing prerequisites
RUN apt-get update \
  && WGET_VERSION=$(apt-cache policy wget | grep Candidate | awk '{print $2}') \
  && BZIP2_VERSION=$(apt-cache policy bzip2 | grep Candidate | awk '{print $2}') \
  && apt-get install -y --no-install-recommends \
  wget="${WGET_VERSION}" \
  bzip2="${BZIP2_VERSION}" \
  && rm -rf /var/lib/apt/lists/*

# Pulling and extracting Manta source code
RUN wget -q --no-check-certificate https://github.com/Illumina/manta/releases/download/v1.6.0/manta-1.6.0.centos6_x86_64.tar.bz2 \
  && tar -jxf manta-1.6.0.centos6_x86_64.tar.bz2

# Installing Manta
WORKDIR /manta-1.6.0.centos6_x86_64
ENV PATH="${PATH}:/manta-1.6.0.centos6_x86_64/bin"

# Cleanup
RUN rm -rf manta-1.6.0.centos6_x86_64.tar.bz2
