
# Using the Ubuntu base image
FROM ubuntu:noble-20240114

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="samtools"
LABEL org.opencontainers.image.description="Docker image for the use of Samtools in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="1.10"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Installing prerequisites
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential=12.10ubuntu1 wget=1.21.4-1ubuntu4 \
  zlib1g-dev=1:1.3.dfsg-3.1ubuntu2 autoconf=2.71-3 automake=1:1.16.5-1.3ubuntu1 \
  libncurses-dev=6.4+20240113-1ubuntu2 libbz2-dev=1.0.8-5.1 liblzma-dev=5.6.1+really5.4.5-1 \
  libssl-dev=3.0.13-0ubuntu3 libcurl4-gnutls-dev=8.5.0-2ubuntu10.1 bedtools=2.31.1+dfsg-2 \
  && rm -rf /var/lib/apt/lists/*

# Pulling and extracting Samtools source code
RUN wget -q --no-check-certificate https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2 && tar -jxf samtools-1.10.tar.bz2

# Installing Samtools
WORKDIR /samtools-1.10
RUN ./configure && make && make install
WORKDIR /

# Cleanup
RUN rm -rf samtools-1.10 samtools-1.10.tar.bz2
