
# Using the Ubuntu base image
FROM ubuntu:noble-20241011

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="biobambam2"
LABEL org.opencontainers.image.description="Container image for the use of biobambam2 in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="2.0.185"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library/biobambam2
LABEL org.opencontainers.image.licenses=MIT

# Installing biobambam2 via apt-get
RUN apt-get update \
  && apt-get install -y --no-install-recommends biobambam2=2.0.185+ds-1 \
  && rm -rf /var/lib/apt/lists/*


