
# Using the Ubuntu base image
FROM ubuntu:24.04

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="annovar"
LABEL org.opencontainers.image.description="Docker image for the use of Annovar using hg19 in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://ocdo.fredhutch.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Set the shell option to fail if any command in a pipe fails
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Installing prerequisites
RUN apt-get update \
  && BE_VERSION=$(apt-cache policy build-essential | grep Candidate | awk '{print $2}') \
  && WGET_VERSION=$(apt-cache policy wget | grep Candidate | awk '{print $2}') \
  && PERL_VERSION=$(apt-cache policy perl | grep Candidate | awk '{print $2}') \
  && apt-get install -y --no-install-recommends \
  build-essential="${BE_VERSION}" \
  wget="${WGET_VERSION}" \
  perl="${PERL_VERSION}" \
  && rm -rf /var/lib/apt/lists/*

# Pulling and extracting Annovar source code
RUN wget -q --no-check-certificate http://www.openbioinformatics.org/annovar/download/0wgxR2rIVP/annovar.latest.tar.gz && tar -xvf annovar.latest.tar.gz
ENV PATH="${PATH}:/annovar"

# Downloading GRCh38 resources
RUN annotate_variation.pl -buildver hg19 -downdb -webfrom annovar refGene /annovar/humandb/ \
  && annotate_variation.pl -buildver hg19 -downdb -webfrom annovar knownGene /annovar/humandb/ \
  && annotate_variation.pl -buildver hg19 -downdb -webfrom annovar cosmic70 /annovar/humandb/ \
  && annotate_variation.pl -buildver hg19 -downdb -webfrom annovar esp6500siv2_all /annovar/humandb/ \
  && annotate_variation.pl -buildver hg19 -downdb -webfrom annovar clinvar_20180603 /annovar/humandb/ \
  && annotate_variation.pl -buildver hg19 -downdb -webfrom annovar gnomad211_exome /annovar/humandb/

# Cleanup
RUN rm -rf annovar.latest.tar.gz


