
# Using the Ubuntu base image
FROM ubuntu:noble-20241011

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="annovar"
LABEL org.opencontainers.image.description="Docker image for the use of Annovar using hg19 in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="hg19"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Installing prerequisites
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential=12.10ubuntu1 wget=1.21.4-1ubuntu4 perl=5.38.2-3.2build2 \
  && rm -rf /var/lib/apt/lists/*

# Pulling and extracting Annovar source code
RUN wget -q --no-check-certificate http://www.openbioinformatics.org/annovar/download/0wgxR2rIVP/annovar.latest.tar.gz && tar -xvf annovar.latest.tar.gz
ENV PATH="${PATH}:/annovar"

# Downloading GRCh38 resources
RUN annotate_variation.pl -buildver hg19 -downdb -webfrom annovar refGene /annovar/humandb/ \
&& annotate_variation.pl -buildver hg19 -downdb -webfrom annovar knownGene /annovar/humandb/ \
&& annotate_variation.pl -buildver hg19 -downdb -webfrom annovar cosmic70 /annovar/humandb/ \
&& annotate_variation.pl -buildver hg19 -downdb -webfrom annovar esp6500siv2_all /annovar/humandb/ \
&& annotate_variation.pl -buildver hg19 -downdb -webfrom annovar clinvar_20180603 /annovar/humandb/ \
&& annotate_variation.pl -buildver hg19 -downdb -webfrom annovar gnomad211_exome /annovar/humandb/

# Cleanup
RUN rm -rf annovar.latest.tar.gz

