# AnnotSV Docker Image for WILDS Docker Library
FROM ubuntu:22.04

# Adding labels for the GitHub Container Registry following WILDS standards
LABEL org.opencontainers.image.title="annotSV"
LABEL org.opencontainers.image.description="Container image for annotSV annotation tool in WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://ocdo.fredhutch.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Set the shell option to fail if any command in a pipe fails
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install dependencies and AnnotSV in one layer
RUN apt-get update \
  && WGET_VERSION=$(apt-cache policy wget | grep Candidate | awk '{print $2}') \
  && TCL_VERSION=$(apt-cache policy tcl | grep Candidate | awk '{print $2}') \
  && MAKE_VERSION=$(apt-cache policy make | grep Candidate | awk '{print $2}') \
  && GCC_VERSION=$(apt-cache policy gcc | grep Candidate | awk '{print $2}') \
  && apt-get install -y --no-install-recommends \
  wget="${WGET_VERSION}" \
  tcl="${TCL_VERSION}" \
  make="${MAKE_VERSION}" \
  gcc="${GCC_VERSION}" \
  && rm -rf /var/lib/apt/lists/*
RUN wget -q --no-check-certificate -O annotsv.tar.gz https://github.com/lgmgeo/AnnotSV/archive/v3.4.4.tar.gz && tar -xzf annotsv.tar.gz
WORKDIR /AnnotSV-3.4.4
RUN make PREFIX=/usr/local install
WORKDIR /
RUN rm -rf AnnotSV-3.4.4 annotsv.tar.gz

CMD ["AnnotSV", "-help"]
