
# Using the Ubuntu base image
FROM ubuntu:24.04

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="cellranger"
LABEL org.opencontainers.image.description="Container image for the use of Cell Ranger in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="10.0.0"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Set the shell option to fail if any command in a pipe fails
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Installing prerequisites
RUN apt-get update \
  && BUILD_ESSENTIAL_VERSION=$(apt-cache policy build-essential | grep Candidate | awk '{print $2}') \
  && WGET_VERSION=$(apt-cache policy wget | grep Candidate | awk '{print $2}') \
  && ZLIB1G_DEV_VERSION=$(apt-cache policy zlib1g-dev | grep Candidate | awk '{print $2}') \
  && AUTOCONF_VERSION=$(apt-cache policy autoconf | grep Candidate | awk '{print $2}') \
  && AUTOMAKE_VERSION=$(apt-cache policy automake | grep Candidate | awk '{print $2}') \
  && LIBNCURSES_DEV_VERSION=$(apt-cache policy libncurses-dev | grep Candidate | awk '{print $2}') \
  && LIBBZ2_DEV_VERSION=$(apt-cache policy libbz2-dev | grep Candidate | awk '{print $2}') \
  && LIBLZMA_DEV_VERSION=$(apt-cache policy liblzma-dev | grep Candidate | awk '{print $2}') \
  && LIBSSL_DEV_VERSION=$(apt-cache policy libssl-dev | grep Candidate | awk '{print $2}') \
  && LIBCURL4_GNUTLS_DEV_VERSION=$(apt-cache policy libcurl4-gnutls-dev | grep Candidate | awk '{print $2}') \
  && apt-get install -y --no-install-recommends \
  build-essential="${BUILD_ESSENTIAL_VERSION}" \
  wget="${WGET_VERSION}" \
  zlib1g-dev="${ZLIB1G_DEV_VERSION}" \
  autoconf="${AUTOCONF_VERSION}" \
  automake="${AUTOMAKE_VERSION}" \
  libncurses-dev="${LIBNCURSES_DEV_VERSION}" \
  libbz2-dev="${LIBBZ2_DEV_VERSION}" \
  liblzma-dev="${LIBLZMA_DEV_VERSION}" \
  libssl-dev="${LIBSSL_DEV_VERSION}" \
  libcurl4-gnutls-dev="${LIBCURL4_GNUTLS_DEV_VERSION}" \
  && rm -rf /var/lib/apt/lists/*

# Download and install Cell Ranger pre-built binary
# Note: Because the key for this link expires, these containers are
# excluded from the automated build-and-push GitHub Action.
# To make changes, provide an updated link and reupload manually.
RUN wget -q --no-check-certificate -O cellranger-10.0.0.tar.gz \
  "https://cf.10xgenomics.com/releases/cell-exp/cellranger-10.0.0.tar.gz?Expires=1766145670&Key-Pair-Id=APKAI7S6A5RYOXBWRPDA&Signature=glFsXIGKiPhvX17igjC5Tc-hK-tz8Xv7WWDOtrPoPnCaRkO2LyWKDk1daxIYHnJHTgfKgX6-Em5AYsFBF-MdYLrMwUS91AwWtJowJuqw9EWaDi5CtniTSyILyq~i2urxkVJ9-~mbUX0KdwP4y447SX87BPV0ZNzrs1lC968dkhsL-Rw8pRjawgfjK9Pb~~S0l1O4esXrRiY8rHAJr5yXqp2rwmakIUVYXFRdCwJUuhMMkLK0rxFJhqNICSTb6fpOGNBwQOn8F1TUaeVOoXdpQ0QvhO5~6Cn2gL8St2JAZo9pGhQalLknuS0ymhUTZEWHcacsPea72WA9jwSDEJc8Tw__" \
  && tar -xzf cellranger-10.0.0.tar.gz \
  && rm -rf cellranger-10.0.0.tar.gz

# Set environment variables
ENV PATH="${PATH}:/cellranger-10.0.0"

# Set working directory
WORKDIR /data

# Smoke test (NOTE: Cell Ranger only works on x86_64 Linux)
RUN cellranger --version
