
# Using the Ubuntu base image
FROM ubuntu:noble-20240114

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="cellranger"
LABEL org.opencontainers.image.description="Container image for the use of Cell Ranger in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Installing prerequisites
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential=12.10ubuntu1 wget=1.21.4-1ubuntu4 \
  zlib1g-dev=1:1.3.dfsg-3.1ubuntu2 autoconf=2.71-3 automake=1:1.16.5-1.3ubuntu1 \
  libncurses-dev=6.4+20240113-1ubuntu2 libbz2-dev=1.0.8-5.1 liblzma-dev=5.6.1+really5.4.5-1 \
  libssl-dev=3.0.13-0ubuntu3.1 libcurl4-gnutls-dev=8.5.0-2ubuntu10.1 \
  && rm -rf /var/lib/apt/lists/*

# Pulling and extracting Cell Ranger source code
RUN wget -q --no-check-certificate -O cellranger-6.0.2.tar.gz \
  "https://cf.10xgenomics.com/releases/cell-exp/cellranger-6.0.2.tar.gz?Expires=1718037805&Key-Pair-Id=APKAI7S6A5RYOXBWRPDA&Signature=kkUm5ag6YEEohqvg6KHzR4RN4wWL3haRIVoPYmF0ZGG32mSScnfvwog-W2UH7i5gRW1joN8ZtYBTDvkNcY--8ULKaGE0CM6uMrF5bURZiqUVRFXEjf2e7OwFwR6RqXchC5GzNCrK4wPnVwoe9m2Qavem5twz2-U7jf8INPZp0OcgwAgwrzsEdkcdhbxkGaRCRoB629cCVmfJnbOaznErUbHzNk4gp2P2pbWlIPDgnrOQDg2jzC7FJPn9tTOH3QuIVYvBeBF~Vj2xCeWFYX1ajmvC~tLywAecUQ6wT0MpNyNVvkygynSJnXENby8DGZXfLLP0JclcoQqe8oKG1VmJhA__" && tar -zxvf cellranger-6.0.2.tar.gz
# Note: Because the key for this link expires, these containers are 
# excluded from the automated build-and-push GitHub Action. 
# To make changes, provide an updated link and reupload manually.

# Installing Cell Ranger
ENV PATH="${PATH}:/cellranger-6.0.2"

# Cleanup
RUN rm -rf cellranger-6.0.2.tar.gz 
