
# Using the Ubuntu base image
FROM ubuntu:noble-20240114

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="bedtools"
LABEL org.opencontainers.image.description="Container image for the use of bedtools in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Installing prerequisites
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential=12.10ubuntu1 bedtools=2.31.1+dfsg-2 \
  && rm -rf /var/lib/apt/lists/*
