

# Using the Nvidia base image
# FROM rocker/tidyverse:3.6.0
FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="rtorch"
LABEL org.opencontainers.image.description="Container image for the use of the Torch R package in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Installing Torch
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update \
  && apt-get install -y --no-install-recommends build-essential=12.9ubuntu3 r-base=4.1.2-1ubuntu2 \
  && rm -rf /var/lib/apt/lists/*
RUN R -e "install.packages('remotes', repos = 'https://cloud.r-project.org', dependencies = TRUE); remotes::install_version('torch', version = '0.13.0', repos = 'https://cloud.r-project.org'); torch::install_torch()"
RUN R -e "install.packages(c('coro', 'smotefamily', 'pacman', 'magick', 'pins', 'torchvision', 'tidyverse'), repos = 'https://cloud.r-project.org', dependencies = TRUE)"
RUN R -e "install.packages(c('torchdatasets', 'tidyverse'), repos = 'https://cloud.r-project.org', dependencies = TRUE)"