
# Using Python base image
FROM python:3.12-slim

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="scanpy"
LABEL org.opencontainers.image.description="Container image for the use of Scanpy library for Single-Cell analysis in Python"
LABEL org.opencontainers.image.version="1.10.2"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://ocdo.fredhutch.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Installing packages via pip
RUN pip install --no-cache-dir scanpy==1.10.2 leiden-clustering==0.1.0

