# Using the miniforge base image
FROM condaforge/miniforge3:24.7.1-2

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="sra-tools"
LABEL org.opencontainers.image.description="Container image for the use of SRA Toolkit in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="latest"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://hutchdatascience.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Switching from hard-links to copies and installing sra-tools, pfastqdump
RUN conda config --set always_copy true \
  && conda install -y -c bioconda sra-tools=3.1.1 parallel-fastq-dump=0.6.7
