# Using Python base image
FROM python:3.12-slim

# Adding labels for the GitHub Container Registry
LABEL org.opencontainers.image.title="bedparse"
LABEL org.opencontainers.image.description="Container image for bedparse - Python module and CLI tool to perform operations on BED files in FH DaSL's WILDS"
LABEL org.opencontainers.image.version="0.2.3"
LABEL org.opencontainers.image.authors="wilds@fredhutch.org"
LABEL org.opencontainers.image.url=https://ocdo.fredhutch.org/
LABEL org.opencontainers.image.documentation=https://getwilds.org/
LABEL org.opencontainers.image.source=https://github.com/getwilds/wilds-docker-library
LABEL org.opencontainers.image.licenses=MIT

# Ensure pipelines fail if any command fails
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install bedparse via pip and verify installation
RUN pip install --no-cache-dir bedparse==0.2.3 \
  && bedparse --help

# Create working directory
WORKDIR /data

# Command to run when container starts
CMD ["/bin/bash"]
