name: Docker Scout

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}
      - name: Docker Scout
        id: docker-scout
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          image: getwilds/bwa:latest
          platform: linux/amd64
          summary: true
          write-comment: true
          keep-previous-comments: true
