name: Docker Scout Update

on:
  workflow_dispatch:
    inputs:
      tool:
        description: 'Tool directory to analyze (leave blank to analyze all tools)'
        required: false
        type: string
  schedule:
    - cron: "0 8 1 * *"
  pull_request: # Testing Purposes
    types: [opened, reopened, synchronize]
    paths:
      - '.github/scripts/docker_scout.py'
      - '.github/workflows/docker-scout.yml'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  docker-scout:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install pyyaml gitpython requests

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

      - name: Run Docker Scout Analysis
        run: python .github/scripts/docker_scout.py ${{ github.event.inputs.tool }}
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
