name: Docker Scout

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true
