name: Docker Scout

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          image: getwilds/bwa:latest
          command: cves,recommendations,compare
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true
