name: Dockerfile Linting

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
          dockerfile: samtools/Dockerfile_*
          failure-threshold: "warning"
