name: Docker Scout Update

on:
  workflow_dispatch:
    inputs:
      tool:
        description: 'Tool directory to analyze (leave blank to analyze all tools)'
        required: false
        type: string
  schedule:
    - cron: "0 8 1 * *"
  # pull_request: # Testing Purposes
  #   types: [opened, reopened, synchronize]
  #   paths:
  #     - '.github/scripts/docker_scout.py'
  #     - '.github/workflows/docker-scout.yml'

jobs:
  docker-scout:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

      - name: Run Docker Scout Analysis
        run: uv run .github/scripts/docker_scout.py ${{ github.event.inputs.tool }}
      
      - name: Generate fresh token for git operations
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: getwilds
          repositories: wilds-docker-library

      - name: Stash changes before fresh checkout
        run: git stash push -u -m "CVE reports and manifest"

      - name: Checkout with fresh token
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
          clean: false

      - name: Restore stashed changes
        run: git stash pop

      - name: Commit CVE Reports
        run: uv run .github/scripts/commit_cve_reports.py
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GH_APP_TOKEN: ${{ steps.generate_token.outputs.token }}
