name: Docker Build, Upload, and Update Descriptions

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      image_directory:
        description: 'Directory name containing the Dockerfile to build/push (e.g., "samtools")'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"
      
      - name: Install Python dependencies
        run: |
          uv pip install gitpython requests
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}
      
      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
      
      - name: Run Docker Update Process
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # Manual trigger - use the specified directory
            uv run .github/scripts/docker_update.py ${{ github.event.inputs.image_directory }}
          else
            # Push event - use git diff logic
            uv run .github/scripts/docker_update.py
          fi
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PW: ${{ secrets.DOCKERHUB_PW }}
